export const types = Object.freeze({
  SET_USER_STATE: 'SET_USER_STATE',

  SET_SIGN_UP_USER_REQUEST: 'SET_SIGN_UP_USER_REQUEST',
  SET_SIGN_UP_USER_SUCCESS: 'SET_SIGN_UP_USER_SUCCESS',
  SET_SIGN_UP_USER_ERROR: 'SET_SIGN_UP_USER_ERROR',

  SET_SIGN_IN_USER_REQUEST: 'SET_SIGN_IN_USER_REQUEST',
  SET_SIGN_IN_USER_SUCCESS: 'SET_SIGN_IN_USER_SUCCESS',
  SET_SIGN_IN_USER_ERROR: 'SET_SIGN_IN_USER_ERROR',

  SET_SIGN_IN_USER_BY_TOKEN_REQUEST: 'SET_SIGN_IN_USER_BY_TOKEN_REQUEST',
  SET_SIGN_IN_USER_BY_TOKEN_SUCCESS: 'SET_SIGN_IN_USER_BY_TOKEN_SUCCESS',
  SET_SIGN_IN_USER_BY_TOKEN_ERROR: 'SET_SIGN_IN_USER_BY_TOKEN_ERROR',

  SET_LOGOUT_USER_REQUEST: 'SET_LOGOUT_USER_REQUEST',
  SET_LOGOUT_USER_SUCCESS: 'SET_LOGOUT_USER_SUCCESS',
  SET_LOGOUT_USER_ERROR: 'SET_LOGOUT_USER_ERROR',

  SET_CREATE_USER_PROFILE_REQUEST: 'SET_CREATE_USER_PROFILE_REQUEST',
  SET_CREATE_USER_PROFILE_SUCCESS: 'SET_CREATE_USER_PROFILE_SUCCESS',
  SET_CREATE_USER_PROFILE_ERROR: 'SET_CREATE_USER_PROFILE_ERROR',

  SET_CHANGE_USER_PROFILE_REQUEST: 'SET_CHANGE_USER_PROFILE_REQUEST',
  SET_CHANGE_USER_PROFILE_SUCCESS: 'SET_CHANGE_USER_PROFILE_SUCCESS',
  SET_CHANGE_USER_PROFILE_ERROR: 'SET_CHANGE_USER_PROFILE_ERROR',

  SET_CHANGE_USER_PASSWORD_REQUEST: 'SET_CHANGE_USER_PASSWORD_REQUEST',
  SET_CHANGE_USER_PASSWORD_SUCCESS: 'SET_CHANGE_USER_PASSWORD_SUCCESS',
  SET_CHANGE_USER_PASSWORD_ERROR: 'SET_CHANGE_USER_PASSWORD_ERROR',
});
