export const asyncTypes = Object.freeze({
  SET_FETCH_SIGN_UP_USER_ASYNC: 'SET_FETCH_SIGN_UP_USER_ASYNC',
  SET_FETCH_SIGN_IN_USER_ASYNC: 'SET_FETCH_SIGN_IN_USER_ASYNC',
  SET_FETCH_SIGN_IN_USER_BY_TOKEN_ASYNC:
    'SET_FETCH_SIGN_IN_USER_BY_TOKEN_ASYNC',
  SET_FETCH_LOGOUT_USER_BY_TOKEN_ASYNC: 'SET_FETCH_LOGOUT_USER_BY_TOKEN_ASYNC',
  SET_FETCH_CHANGE_USER_PASSWORD_ASYNC: 'SET_FETCH_CHANGE_USER_PASSWORD_ASYNC',
});
